version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      actions-all:
        applies-to: version-updates
        patterns:
          - "*"
      actions-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      npm-all:
        applies-to: version-updates
        patterns:
          - "*"
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      pip-all:
        applies-to: version-updates
        patterns:
          - "*"
      pip-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      terraform-all:
        applies-to: version-updates
        patterns:
          - "*"
      terraform-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      gomod-all:
        applies-to: version-updates
        patterns:
          - "*"
      gomod-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      docker-all:
        applies-to: version-updates
        patterns:
          - "*"
      docker-security:
        applies-to: security-updates
        patterns:
          - "*"
