version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      github-actions:
        applies-to: version-updates
        patterns:
          - "*"
      github-actions-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      npm:
        applies-to: version-updates
        patterns:
          - "*"
      npm-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      pip:
        applies-to: version-updates
        patterns:
          - "*"
      pip-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      terraform:
        applies-to: version-updates
        patterns:
          - "*"
      terraform-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      go:
        applies-to: version-updates
        patterns:
          - "*"
      go-security:
        applies-to: security-updates
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      docker:
        applies-to: version-updates
        patterns:
          - "*"
      docker-security:
        applies-to: security-updates
        patterns:
          - "*"
